language: objective-c  #1
osx_image: xcode11.3.1 #2

jobs:
  include:
    - script: xcodebuild clean build test -project NJImageExtensions.xcodeproj -scheme NJImageExtensions -destination "platform=iOS Simulator,name=iPhone 8,OS=11.2" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
